# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo Italiano')),
                ('marker', models.ImageField(blank=True, null=True, upload_to='markers')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colore Linea')),
                ('mappa', models.FileField(blank=True, null=True, upload_to='uploads/kml/')),
            ],
            options={
                'verbose_name_plural': 'Import KML',
            },
        ),
    ]
