# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='path',
            options={'verbose_name_plural': 'Descrizione Giornate'},
        ),
        migrations.RemoveField(
            model_name='path',
            name='color',
        ),
        migrations.AddField(
            model_name='path',
            name='colore',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Colore Riferimento Percorso'),
        ),
        migrations.AlterField(
            model_name='path',
            name='mappa',
            field=models.FileField(blank=True, null=True, upload_to='uploads/klm/'),
        ),
        migrations.AlterField(
            model_name='path',
            name='marker',
            field=models.ImageField(blank=True, null=True, upload_to='marker'),
        ),
    ]
