# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml', '0004_auto_20160312_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='mappa_due',
            field=models.FileField(blank=True, null=True, upload_to='uploads/klm_due/'),
        ),
    ]
