# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml', '0005_path_mappa_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='mappa_due',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
