# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml', '0009_auto_20160312_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='mappa',
            field=models.FileField(blank=True, null=True, upload_to='uploads/klm/'),
        ),
    ]
