# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml', '0010_auto_20160312_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='kml_ok',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo Italiano'),
        ),
    ]
