# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kml', '0012_auto_20160312_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='kml_ok',
        ),
    ]
