# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml', '0015_auto_20160312_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='kml_ok',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='uploads/kml/'),
        ),
    ]
